title: EmbeddedCLI
description: Embedded CLI | Open and Lightweight Command Line Interface for Embedded Systems.

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Walid Amriou
repo_url: 'https://github.com/walidamriou/EmbeddedCLI'
edit_on_github: false
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
