site_name: 'EmbeddedCLI'
site_description: 'Embedded CLI | Open and Lightweight Command Line Interface for Embedded Systems.'
repo_url: 'https://github.com/walidamriou/EmbeddedCLI'
repo_name: 'GitHub'
docs_dir: 'docs/'
site_dir: '_site_mkdocs/'
theme: 'readthedocs'
prev_next_buttons_location: 'both'
copyright: 'Walid Amriou'
